services:
  shm-client:
    image: ${IMAGE:-ghcr.io/dignezzz/shm-client-4-client-2:latest}
    ports:
      - "3001:80"
    environment:
      SHM_URL: "https://api.mydomain.com"
      APP_NAME: "My Company"
      APP_DESCRIPTION: "My Company Description"
    restart: unless-stopped
